config/routes.rb
Rails.application.routes.draw do
  resources :bookings
					#for user registration this line takes controller to given path	first.
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  resources :welcome ,except:[:destroy, :update,:create]
  resources :venues 


 

  

  root 'welcome#index'
  get 'home', to: 'welcome#home'
 get "check", to: "welcome#check"
 get 'approve_requests', to: "venues#approve_requests"
 get 'user_request', to: "venues#user_request"  
 get 'all_bookings', to: 'venues#all_bookings'
 get 'cancel_request', to: 'venues#cancel_request'

  
  #post 'show_venue_detail', to: 'welcome#show_venue_detail'
  #get 'show_venue_details', to: 'bookings#show_venue_details'
  #routes for venues
  #resources :welcome
  
end

app/models/booking.rb
class Booking < ApplicationRecord
	belongs_to :venue
	belongs_to :user
	validates :from, presence: true
      validates :to, presence:true
      validates :on, presence:true
      validates :user_id, presence: true
      validates :venue_id, presence:true

     
      

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  # GET /bookings
  # GET /bookings.json
  def index
    @bookings = Booking.all
  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end

  # POST /bookings
  # POST /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking request is sent.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1
  # PATCH/PUT /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking.destroy
    respond_to do |format|
      format.html { redirect_to bookings_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.permit(:venue_id, :user_id, :from, :to, :on)
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="col-md-5">
  <ul class="list-group col-md-5 col-off-set-2">
  <li class="list-group-item alert alert-success"><strong>Name:</strong>  <%= @booking.venue.title %></li>
  <li class="list-group-item list-group-item-secondary"> <strong>City/town:</strong> <%=@booking.venue.place%></li>
  <li class="list-group-item list-group-item-secondary"><strong>Landmark:</strong>  <%=@booking.venue.landmark%></li>
  <li class="list-group-item list-group-item-secondary"><strong>  street address:</strong> <%=@booking.venue.street_address%></li>
  <li class="list-group-item list-group-item-secondary"><strong>contact number:</strong> <%=@booking.venue.contact_number%></li>
</ul>
</div>

  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end -%>
    <%= form_for(@booking, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="col-md-3"> 
          <%= f.label :from %>
          <%= f.select(:from,options_for_select(['','9:00AM','10:00AM','11:00AM', '12:00PM','1:00PM','2:00PM','3:00PM','4:00PM','5:00AM','6:00PM','7:00PM','8:00AM','9:00PM','10:00PM']), class: 'form-control') %>
        </div>
         <div class="col-md-3"> 
          <%= f.label :to %>
          <%= f.select(:to,options_for_select(['',"9:00AM",'10:00AM','11:00AM', '12:00PM','1:00PM','2:00PM','3:00PM','4:00PM','5:00AM','6:00PM','7:00PM','8:00AM','9:00PM','10:00PM']), class: 'form-control') %>
          
        </div>
       <%= f.date_select(:on) %>
      </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Update this Booking</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1> Your Bookings</h1>
<table border="1px">
  <thead>
    <tr>
      <th>Venue</th>
      <th>City/town</th>
      <th>Street Adrdess</th>
      <th>Landmark</th>
      <th>Contact No</th>
       <th>From</th>
        <th>To</th>
        <th>On</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.venue.title %></td>
        <td><%= booking.venue.place %></td>
        <td><%= booking.venue.street_address %></td>
        <td><%= booking.venue.landmark %></td>
        <td><%= booking.venue.contact_number %></td>
        <td><%= booking.venue.from %></td>
        <td><%= booking.venue.to %></td>
        <td><%= booking.on %></td>
        <td><%= link_to 'Show', booking %></td>
        <td><%= link_to 'update', edit_booking_path(booking) %></td>
        <td><%= link_to 'Cancel', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Booking', new_booking_path %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
    <% end -%>
    <div class="">
        <div class="col-md-6">
         
          <%= params['from']%>
        </div> 
          
          <div class="col-md-6">
         
          <%= params['to']%>
        </div> 
         <div class="col-md-6"> 
      
       <%= params['name'] %>
      </div>

     <%= form_for(@booking,  :html => {class: "form-horizontal", role: "form"}) do |f|  %>
     <%= f.hidden_field_tag :to, params['to'] %>
     <%= f.hidden_field_tag :from, params['from'] %>
     <%= f.hidden_field_tag :venue_id, params['venue_id'] %>
     <%= f.hidden_field_tag :user_id, params['user'] %>
     <%= f.hidden_field_tag :on, params['on'] %>
      
  	<div class="">
    <%= f.submit %>
  	</div>
	<% end %>


  

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<h3 align="center">Name : <%= @booking.venue.title %></h3>
	<div>
		<h4 align="center">Place :<%= @booking.venue.place %> </h4>	

	</div>
	<div>
		<h4 align="center">Street Address :<%= @booking.venue.street_address %> </h4>	

	</div>
	<div>
		<h4 align="center">Landmark :<%= @booking.venue.landmark %> </h4>	

	</div>
	<div>
		<h4 align="center">Contact No :<%= @booking.venue.contact_number %> </h4>	

	</div>
	<div>
		<h4 align="center">from :<%= @booking.from %> </h4>	

	</div>
		<div>
		<h4 align="center">To :<%= @booking.to %> </h4>	

	</div>
	<div>
		<h4 align="center">On :<%= @booking.on %> </h4>	

	</div>


   	<%= link_to "Update this booking" , edit_booking_path(@booking), class: "btn btn-xs btn-primary" %>
			<%= link_to "Cancel this booking", booking_path(@booking), method: :delete, data: {confirm: "Are you sure you want to cancel this booking ?"}, class: "btn btn-xs btn-danger" %>
			<%= link_to "View all bookings" ,bookings_path, class: "btn btn-xs btn-success" %>

		   