config/routes.rb
Rails.application.routes.draw do
  resources :bookings
					#for user registration this line takes controller to given path	first.
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  resources :welcome ,except:[:destroy, :update,:create]
  resources :venues 


 

  

  root 'welcome#index'
  get 'home', to: 'welcome#home'
 get "check", to: "welcome#check"
 get 'approve_requests', to: "venues#approve_requests"
 get 'user_request', to: "venues#user_request"  
 get 'all_bookings', to: 'venues#all_bookings'
 get 'cancel_request', to: 'venues#cancel_request'

  
  #post 'show_venue_detail', to: 'welcome#show_venue_detail'
  #get 'show_venue_details', to: 'bookings#show_venue_details'
  #routes for venues
  #resources :welcome
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
  def index
  	redirect_to home_path if !current_user.venue_admin?
  end

  def home
    @venue_found = Venue.all
    if @venue_found
     #render 'new'
    else
     render status: :not_found, head: true
      end
  end
       # displays venue detail
  def show
         @venue = Venue.find(params[:id])
        if @venue
          "HOLA!!"
        end
  end

  def check
      if params[:venue_detail]
      @venue_found = Venue.find(params[:venue_detail])
      @timings = Venue.where("from: :from",{from: params['from']})
      end
      if @timings
      #render json: @venue
      render partial: 'check'
      
      else
      render status: :not_found, nothing: true
     end
  end

  def new
    if params[:venue]
      @venue = user.Venue.find(params[:venue])
      @venue ||= venue.new_from_lookup(params[:venue])      
    end

    if @venue
      render json: @venue
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
    end
    def edit
      
    end

    def update
      if @article.update(article_params)
      flash[:success] = "Article was successfully updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end      
    end

    def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end



end

app/views/welcome/_check.html.erb
<% if  @venue_found %>
    <div id="venue_availability-results" class="well results-block">
      <strong>From:</strong><%= @venue_found.from %>
      <strong>To:</strong><%= @venue_found.to %>
      <strong>On:</strong><%= params[:name] %>
    </div>

    <% if current_user.can_send_request?(@venue_found) %>
    			<h3>Its available, follow the link and send request</h3>
				<%= link_to  "send request to book this venue",new_booking_path(user: current_user, venue_id: @venue_found.id,from:@venue_found.from,to:@venue_found.to, on: params[:name]), class: 'btn btn-success btn-xs', method: :get, action: :create%>
				<% else %>
					<span class="label label-default">
						request cannot be send because you have already sent
						<% if !current_user.under_limit? %>
							3 requests
						<%end %>
						<% if current_user.request_already_sent?(@venue_found.id) %>

							 request
						<%end %>

					</span>

				<% end %>

    <div id="venue-lookup-errors">
      
    </div>
  <% end %>
</div>

app/views/welcome/home.html.erb
<h1 align="center">LIsting all venue </h1>
<% @venue_found.each do |venue| %>
<%#= @venue_found.inspect %>
<!-- only venue admin can see their own venue_found -->
 <% if user_signed_in? && !current_user.venue_admin?%>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div>
          <%= link_to venue.title,  welcome_path(venue) %>
      </div>
      <div>
         <%= truncate(venue.place, lenght:50) %>
          <div>
            <small>
            Created at
                <%= time_ago_in_words(venue.created_at) %> ago,
              Last updated at: <%= time_ago_in_words(venue.updated_at) %> ago. 
            </small>
          </div>
      </div>
     
      <div class="venue-actions">

        
        <%= link_to "book", welcome_path(venue) %> 
         <%= link_to "Show", check_path(venue) %> 
      </div> 
    <%end %>
    </div>
  </div>
</div> 
<% end %>

app/views/welcome/index.html.erb
<h1>THIS IS HOME PAGE </h1>
<div class="jumbotron">
  <h1 class="display-3">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

app/views/welcome/new.html.erb
  <% if @venue.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@booking.errors.count, "error") %>
              prohibited this venue from displaying: 
            </h2> 
            <div class="panel-body">
              <ul>
                 <% @booking.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <%end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end %>
<%= form_for(@booking, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :created_at %>
        </div>
        <div class="col-sm-8">
          <%= f.text_field :created_at, class: "form-control",placeholder: "Enter booking name", autofocus: true %> 
        </div>
      </div>

      
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>  
      <% end %>
        <div class="col-sm-4 col-sm-offset-4">
          [<%= link_to "Cancel and go back Venues", bookings_path %>]
        </div>
        <% end -%>

  

app/views/welcome/show.html.erb
  
<div class="col-md-4">
<%= form_tag check_path,remote: :true,method: :get, id: 'venue-availability-form',class: ' form-inline' do %>
    <div class=" row ">
      <div class="">
      <%= hidden_field_tag :venue_detail, @venue.id %>
      </div>

      <div class="col-auto"> 
          <%= label_tag :from %>
          <%= select_tag(:from,options_for_select(['9:00AM','10:00AM','11:00AM', '12:00PM','1:00PM','2:00PM','3:00PM','4:00PM','5:00AM','6:00PM','7:00PM','8:00AM','9:00PM','10:00PM']), class: 'form-control') %>
        </div>
         <div class="col-auto"> 
          <%= label_tag :to %>
          <%= select_tag(:to,options_for_select(['',"9:00AM",'10:00AM','11:00AM', '12:00PM','1:00PM','2:00PM','3:00PM','4:00PM','5:00AM','6:00PM','7:00PM','8:00AM','9:00PM','10:00PM']), class: 'form-control select') %>
        </div>
        <div class="col-auto" >
           <%= label_tag :on %>
        <%=  date_field_tag ('name')%> 
        </div>
      <div class="col" style="padding-top: 10px;">
      <%= button_tag(type: :submit, class: "btn btn-md btn-success") do %>
        <span class=""> Check availability</span>
      <%end %>
      </div>
    </div>
  <% end %>
  </div>
  </div>
   <hr/>
   <%=render'common/spinner' %>
  
  
  <div id="venue-availability">
</div>