config/routes.rb
Rails.application.routes.draw do
  resources :bookings
					#for user registration this line takes controller to given path	first.
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  resources :welcome ,except:[:destroy, :update,:create]
  resources :venues 


 

  

  root 'welcome#index'
  get 'home', to: 'welcome#home'
 get "check", to: "welcome#check"
 get 'approve_requests', to: "venues#approve_requests"
 get 'user_request', to: "venues#user_request"  
 get 'all_bookings', to: 'venues#all_bookings'
 get 'cancel_request', to: 'venues#cancel_request'

  
  #post 'show_venue_detail', to: 'welcome#show_venue_detail'
  #get 'show_venue_details', to: 'bookings#show_venue_details'
  #routes for venues
  #resources :welcome
  
end

app/models/venue.rb
class Venue < ActiveRecord::Base
	#many venues can belong to one user
	belongs_to :user,:class_name => 'User'
  has_many :bookings
  has_many :booker, through: :bookings, source: :user
  validates :title, presence: true, length: {minimum:3 , maximum:50}
  validates :place, presence: true, length: {minimum:5 , maximum:50}
  validates :street_address, presence: true, length: {minimum:3 , maximum:30}
    validates :contact_number, presence: true, length: {minimum:6 , maximum:10}
      validates :landmark, presence: true, length: {minimum:3 , maximum:20}
      #debugger
      validates :from, presence: true
      validates :to, presence:true
      validates :from_date, presence:true
      validates :till_date, presence:true
  validates :user_id, presence: true 
    time_array = ['8:00AM','9:00AM','10:00AM','11:00AM',
     '12:00PM','1:00PM','2:00PM','3:00PM',
     '4:00PM','5:00AM','6:00PM','7:00PM','8:00PM',
      '9:00PM','10:PM','11:PM','12:00AM']
    def  self.find_by_availabilty(details)
      where(from: details)
    end


    def self.find_timing
      where(:from)
    end
  
      

 # def self.find_venue_by_id(venue_id)
  #  where(venue_id: venue_id).first
 # end
end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController
before_action :set_venue, only: [:edit, :update, :show, :destroy]
before_action :require_venue_admin, only: [:edit, :update, :show, :destroy,:new, :index]
before_action :require_same_venue_admin, only: [:edit, :update, :show, :destroy,]

def new
@venue = Venue.new
end

def edit

end

def index
  @venues = Venue.all
end

def update
  if @venue.update(venue_params)
      flash[:notice] = "Successfully updated..."
      redirect_to venue_path(@venue)
    else
      render 'edit'
  end
end

def create
#render plain: params[:venue]
#validation
#debugger
  @venue = Venue.new(venue_params)
  @venue.user = current_user
    if @venue.save

    #do validations
    flash[:notice] = "Venue was successfully created..."
    redirect_to venue_path(@venue)
    else
      flash[:danger] = "Venue creation failed..."
    #render new template again
    render 'new'
    end
#create new instance varibale , pass the params and save it
#
#@venue.save

end

def show

end

def approve_requests
   @booking = Booking.find(params['format'])
   if @booking
    @booking.update_attribute(:request,true)
    # @booking.save
  end  
end

def user_request

  @bookings = Booking.where(request: false)
end

def cancel_request

  @booking = Booking.find(params['format'])
   if @booking
    @booking.update_attribute(:request,false)
    # @booking.save
  end  

end

def all_bookings
  @bookings = Booking.all
end

def destroy

  @venue.destroy
  flash[:danger] = "Venue Successfully Deleted..."
  redirect_to venues_path
end
  #define private method to safely pass the params
  private
    def venue_params
        params.require(:venue).permit(:title, :place,:street_address, :landmark,:contact_number,:from,:to,:from_date,:till_date)
    end

  def set_venue
    @venue = Venue.find(params[:id])
  end
  def require_venue_admin
    if !current_user.venue_admin?
      flash[:danger] = "Access denied"
      redirect_to root_path
    end
  end
 def require_same_venue_admin
    if current_user != @venue.user
      flash[:danger] = "Access denied"
      redirect_to root_path
    end
  end


end #end of class

app/views/venues/_form.html.erb
  <% if @venue.errors.any? %>
    <div class="row">
      <div class="col-xs-8 col-xs-offset-2">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h2 class="panel-title">
              <%= pluralize(@venue.errors.count, "error") %>
              prohibited this venue from beaing saved:
            </h2> 
            <div class="panel-body">
              <ul>
                <% @venue.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <%end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  <%end %>
<div class="row">
  <div class="col-xs-10 col-md-offset-2">
      <%= form_for(@venue, :html => {class: "form-horizontal", role: "form"}) do |f| %>
         <div class="form-group">
        <div class="col-md-6 ">
          <%= f.label :title%>
          <%= f.text_field :title, auto_foucs: true, class: 'form-control', placeholder: "venue's name" %>
        </div> 
        <div class="col-md-6"> 
          <%= f.label :place %>
          <%= f.text_field :place, class: 'form-control',placeholder: "city/town" %>
        </div>
      </div>
        <!--custom-->
        <div class="form-group">
        <div class="col-md-6 ">
          <%= f.label :street_address %>
          <%= f.text_field :street_address, class: 'form-control' %>
        </div> 
        <div class="col-md-6"> 
          <%= f.label :landmark %>
          <%= f.text_field :landmark, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        
        <div class="col-md-6"> 
          <%= f.label :contact_number %>
          <%= f.text_field :contact_number, class: 'form-control' %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-3"> 
          <%= f.label :from %>
          <%= f.select(:from,options_for_select(['9:00AM','10:00AM','11:00AM', '12:00PM','1:00PM','2:00PM','3:00PM','4:00PM','5:00AM','6:00PM','7:00PM','8:00AM','9:00PM','10:00PM']), class: 'form-control') %>
          <%= f.date_select(:from_date) %>
        </div>
         <div class="col-md-3"> 
          <%= f.label :to %>
          <%= f.select(:to,options_for_select(['',"9:00AM",'10:00AM','11:00AM', '12:00PM','1:00PM','2:00PM','3:00PM','4:00PM','5:00AM','6:00PM','7:00PM','8:00AM','9:00PM','10:00PM']), class: 'form-control') %>
          <%= f.date_select(:till_date) %>
        </div>
       
      </div>
          <div class="form-group">
              <div class="col-sm-offset-5 col-sm-10">
                <%= f.submit class: "btn btn-primary btn-lg"%>
              </div>
          </div>
      <% end %>

      <%= link_to "Back to venue listing", venues_path %>
  </div>
</div>

app/views/venues/all_bookings.html.erb
<h1> All Bookings</h1>
<table border="1px">
  <thead>
    <tr>
      <th>Venue</th>
      <th>City/town</th>
      <th>Street Adrdess</th>
      <th>Landmark</th>
      <th>Contact No</th>
       <th>From</th>
        <th>To</th>
        <th>On</th>
        <th>Status</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.venue.title %></td>
        <td><%= booking.venue.place %></td>
        <td><%= booking.venue.street_address %></td>
        <td><%= booking.venue.landmark %></td>
        <td><%= booking.venue.contact_number %></td>
        <td><%= booking.venue.from %></td>
        <td><%= booking.venue.to %></td>
        <td><%= booking.on %></td>
        <%if !booking.request? %>
          <td>Request Pending</td>
          <%else %>
          <td>Booking Confirmed</td>
         <% end %>
        <td><%= link_to 'Cancel request', cancel_request_path(booking), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'BACK', root_path %>

app/views/venues/edit.html.erb
<h1>Edit existing Venue </h1>
<!--form partial -->
<%= render 'form' %>

app/views/venues/index.html.erb
<h1 align="center">LIsting all your venues </h1>
<p>
<%= link_to "Create new venue", new_venue_path %>
</p>
<% @venues.each do |venue| %>
<!-- only venue admin can see their own venues -->
 <% if user_signed_in? && current_user == venue.user && current_user.venue_admin?%>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      <div>
          <%= link_to venue.title, venue_path(venue) %>
      </div>
      <div>
         <%= truncate(venue.place, lenght:50) %>
          <div>
            <small>
            Created at
                <%= time_ago_in_words(venue.created_at) %> ago,
              Last updated at: <%= time_ago_in_words(venue.updated_at) %> ago. 
            </small>
          </div>
      </div>
     
      <div class="venue-actions">
        <%= link_to "Edit", edit_venue_path(venue) %>
        <%= link_to "Show", venue_path(venue) %> 
        <%= link_to "Delete", venue_path(venue), method: :delete, data: {confirm: "Are you sure ?" }  %> 
      </div> 
    <%end %>
    </div>
  </div>
</div> 
<% end %>

app/views/venues/new.html.erb
<h1 align="center">CREATE NEW VENUE</h1>
<!--form partial -->
<%= render 'form' %>

app/views/venues/show.html.erb
<h1 align="center">Title : <%= @venue.title %></h1>
	<div>
		<h4 align="center">Place :<%= @venue.place %> </h4>	

	</div>
	<div>
		<h4 align="center">Street Address :<%= @venue.street_address %> </h4>	

	</div>
	<div>
		<h4 align="center">Landmark :<%= @venue.landmark %> </h4>	

	</div>
	<div>
		<h4 align="center">Contact No :<%= @venue.contact_number %> </h4>	

	</div>
	<div>
		<h4 align="center">Available from :<%= @venue.from %> </h4>	

	</div>
		<div>
		<h4 align="center">To :<%= @venue.to %> </h4>	

	</div>
	<div>
		<h4 align="center">On :<%= @venue.from_date %> </h4>	

	</div>
		<div>
		<h4 align="center">Till :<%= @venue.till_date %> </h4>	

	</div>

   	 <div>
		   <%= link_to "Edit this venue" , edit_venue_path(@venue), class: "btn btn-xs btn-primary" %>
			<%= link_to "Delete this venue", venue_path(@venue), method: :delete, data: {confirm: "Are you sure you want to delete this venue ?"}, class: "btn btn-xs btn-danger" %>
			<%= link_to "View all venues" ,venues_path, class: "btn btn-xs btn-success" %>

	</div>

app/views/venues/user_request.html.erb
<% if  @bookings.count==0 %>
  <h2>NO requests</h2>
<% else %>
<h1> Bookings request</h1>
<table border="1px">
  <thead>
    <tr>
      <th>Venue</th>
      <th>City/town</th>
      <th>Street Adrdess</th>
      <th>Landmark</th>
      <th>Contact No</th>
       <th>From</th>
        <th>To</th>
        <th>On</th>
        <th>Status</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
        <td><%= booking.venue.title %></td>
        <td><%= booking.venue.place %></td>
        <td><%= booking.venue.street_address %></td>
        <td><%= booking.venue.landmark %></td>
        <td><%= booking.venue.contact_number %></td>
        <td><%= booking.venue.from %></td>
        <td><%= booking.venue.to %></td>
        <td><%= booking.on %></td>
        <%if !booking.request? %>
          <td>Request Pending</td>
          <%else %>
          <td>Booking Confirmed</td>
         <% end %>
        <td><%= link_to 'Approve', approve_requests_path(booking) %>
        <td><%= link_to 'Cancel Request', cancel_request_path(booking), data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% end -%>
<%#= link_to 'BACK', root_path %>