config/routes.rb
Rails.application.routes.draw do
  resources :bookings
					#for user registration this line takes controller to given path	first.
  devise_for :users, :controllers => { :registrations => "user/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #route for home page
  resources :welcome ,except:[:destroy, :update,:create]
  resources :venues 


 

  

  root 'welcome#index'
  get 'home', to: 'welcome#home'
 get "check", to: "welcome#check"
 get 'approve_requests', to: "venues#approve_requests"
 get 'user_request', to: "venues#user_request"  
 get 'all_bookings', to: 'venues#all_bookings'
 get 'cancel_request', to: 'venues#cancel_request'

  
  #post 'show_venue_detail', to: 'welcome#show_venue_detail'
  #get 'show_venue_details', to: 'bookings#show_venue_details'
  #routes for venues
  #resources :welcome
  
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Venue Bookings", root_path, class: "navbar-brand" %>  
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
      <% if user_signed_in? && current_user.venue_admin? %>
        <li><%= link_to "Your Venues", venues_path %></li>
        <li><%= link_to "User requests", user_request_path  %>
        <li><%= link_to "All Bookings", all_bookings_path  %></li>
        <% end %>
        <% if user_signed_in? && !current_user.venue_admin? %>
        <li><%= link_to "Your Bookings", bookings_path %></li>
                  
        </li>
        <%end %>
        <li><%= link_to "Link3", "/path3"  %></li>
      </ul>
      <!--
      <ul class="nav navbar-nav navbar-right">
      <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>-->
    <ul class="nav navbar-nav navbar-right">
    <% if user_signed_in? %>
    <li><%= link_to current_user.full_name %></li>
    <li><%= link_to("Logout", destroy_user_session_path, method: :delete)%></li>
    <% else %>
    
        <li><%= link_to "Log in", new_session_path(resource_name)%></li>
        <li><%= link_to "Sign up", new_registration_path(resource_name) %></li>
    <% end %>
    </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "VenueBooking" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navbar' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">

          <%= bootstrap_flash %>
          <%= yield %>
        </div>

        <div class="col-lg-3">
          <!--
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>--><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>
      <%= debug(params) if Rails.env.development? %>
    </div> <!-- /container -->

  </body>
</html>